version: '3.8'
services:
  pg:
    image: postgres:alpine
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
